export type TaskTemplateConfig = {
  id: string;
  title: string;
  category: string;
  difficulty: "tiny" | "small" | "medium" | "large" | "huge";
  repeatable: boolean;
  estimatedMinutes: number;
  description?: string;
  maxInstances?: number;
};

export const TASK_TEMPLATES: Record<string, TaskTemplateConfig> = {
  course_ququ_20m: {
    id: "course_ququ_20m",
    title: "看曲曲课程 20 分钟",
    category: "learning",
    difficulty: "medium",
    repeatable: true,
    estimatedMinutes: 20,
    description: "专注收看曲曲课程片段",
  },
  course_kaizhi_20m: {
    id: "course_kaizhi_20m",
    title: "看开智课程 20 分钟",
    category: "learning",
    difficulty: "medium",
    repeatable: true,
    estimatedMinutes: 20,
    description: "学习开智课程并记录要点",
  },
  course_notes_15m: {
    id: "course_notes_15m",
    title: "课程笔记整理 15 分钟",
    category: "learning",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 15,
    description: "整理课程笔记与复盘要点",
  },
  read_book_30m: {
    id: "read_book_30m",
    title: "阅读一本书 30 分钟",
    category: "learning",
    difficulty: "medium",
    repeatable: true,
    estimatedMinutes: 30,
    description: "沉浸式阅读与摘要",
  },
  tidy_room_10m: {
    id: "tidy_room_10m",
    title: "整理房间 10 分钟",
    category: "cleaning",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 10,
    description: "快速收拾房间和桌面",
  },
  throw_trash_1bag: {
    id: "throw_trash_1bag",
    title: "丢一袋垃圾",
    category: "cleaning",
    difficulty: "tiny",
    repeatable: true,
    estimatedMinutes: 5,
    description: "清理垃圾并保持清爽",
  },
  clean_desk_15m: {
    id: "clean_desk_15m",
    title: "清理桌面 15 分钟",
    category: "cleaning",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 15,
    description: "清洁桌面、归位物品",
  },
  wash_clothes_30m: {
    id: "wash_clothes_30m",
    title: "洗衣/晾衣 30 分钟",
    category: "cleaning",
    difficulty: "medium",
    repeatable: true,
    estimatedMinutes: 30,
    description: "洗衣、晾衣并整理",
  },
  work_night_shift: {
    id: "work_night_shift",
    title: "上一班夜场",
    category: "work",
    difficulty: "large",
    repeatable: true,
    estimatedMinutes: 300,
    description: "完成夜场工作班次",
  },
  work_night_shift_plus: {
    id: "work_night_shift_plus",
    title: "夜场加班 2 小时",
    category: "work",
    difficulty: "huge",
    repeatable: true,
    estimatedMinutes: 120,
    description: "夜场延长班次",
  },
  work_live_120m: {
    id: "work_live_120m",
    title: "直播/副业 120 分钟",
    category: "work",
    difficulty: "large",
    repeatable: true,
    estimatedMinutes: 120,
    description: "专注完成两小时工作",
  },
  english_10m: {
    id: "english_10m",
    title: "英语接触 10 分钟",
    category: "english",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 10,
    description: "听读英文内容",
  },
  english_words_5: {
    id: "english_words_5",
    title: "背 5 个单词",
    category: "english",
    difficulty: "tiny",
    repeatable: true,
    estimatedMinutes: 5,
    description: "快速记忆新词汇",
  },
  english_listen_20m: {
    id: "english_listen_20m",
    title: "英文听力 20 分钟",
    category: "english",
    difficulty: "medium",
    repeatable: true,
    estimatedMinutes: 20,
    description: "提升听力输入",
  },
  stretch_10m: {
    id: "stretch_10m",
    title: "拉伸舒展 10 分钟",
    category: "health",
    difficulty: "tiny",
    repeatable: true,
    estimatedMinutes: 10,
    description: "缓解疲劳，提升精力",
  },
  walk_30m: {
    id: "walk_30m",
    title: "户外散步 30 分钟",
    category: "health",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 30,
    description: "轻量运动与放松",
  },
  cook_meal_30m: {
    id: "cook_meal_30m",
    title: "做一顿正餐",
    category: "health",
    difficulty: "medium",
    repeatable: true,
    estimatedMinutes: 30,
    description: "自制健康餐食",
  },
  context_change_library: {
    id: "context_change_library",
    title: "去图书馆坐下打开电脑",
    category: "context",
    difficulty: "tiny",
    repeatable: true,
    estimatedMinutes: 15,
    description: "切换到学习环境",
  },
  context_change_cafe: {
    id: "context_change_cafe",
    title: "去咖啡馆进入专注模式",
    category: "context",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 20,
    description: "切换环境进入状态",
  },
  explore_market_30m: {
    id: "explore_market_30m",
    title: "外出采购/探索 30 分钟",
    category: "explore",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 30,
    description: "补给与探索任务",
  },
  reflection_15m: {
    id: "reflection_15m",
    title: "复盘/日记 15 分钟",
    category: "learning",
    difficulty: "small",
    repeatable: true,
    estimatedMinutes: 15,
    description: "写下今日复盘与感受",
  },
};
