export const ACHIEVEMENTS_CONFIG = [
  {
    id: "course_3days",
    name: "点亮第一盏灯",
    description: "连续 3 天完成看课任务",
    icon: "🕯️",
    type: "AUTO",
    condition: { kind: "course_streak", value: 3 },
    reward: {
      coins: 30,
      stats: { sanity: 5 },
      claimName: "🕯️ 第一盏灯徽章",
    },
  },
  {
    id: "course_7days",
    name: "荒野学徒",
    description: "连续 7 天完成看课任务",
    icon: "📜",
    type: "AUTO",
    condition: { kind: "course_streak", value: 7 },
    reward: {
      coins: 60,
      stats: { sanity: 8 },
      claimName: "📜 荒野学徒徽章",
    },
  },
  {
    id: "course_daily_3",
    name: "爆肝研究员",
    description: "单日完成看课任务 ≥ 3 节",
    icon: "📚",
    type: "AUTO",
    condition: { kind: "course_daily", value: 3 },
    reward: {
      coins: 40,
      stats: { sanity: 6 },
    },
  },
  {
    id: "no_junk_food_3",
    name: "暴食怪克星 Lv1",
    description: "拒绝垃圾食品 3 次",
    icon: "🥗",
    type: "AUTO",
    condition: { kind: "tag_count", value: 3, extra: { tag: "no_junk_food" } },
    reward: {
      coins: 25,
      stats: { life: 6 },
    },
  },
  {
    id: "nightclub_no_shift2_30",
    name: "精神守护者",
    description: "连续 30 天没有二班",
    icon: "🌙",
    type: "AUTO",
    condition: { kind: "no_tag_days", value: 30, extra: { tag: "nightclub_shift2" } },
    reward: {
      coins: 80,
      stats: { sanity: 6 },
    },
  },
  {
    id: "room_cleanup_20",
    name: "净化者徽章",
    description: "完成房间垃圾清理 20 次",
    icon: "🧹",
    type: "AUTO",
    condition: { kind: "tag_count", value: 20, extra: { tag: "room_cleanup" } },
    reward: {
      coins: 50,
      stats: { sanity: 8, life: 6 },
      claimName: "🧹 净化者徽章",
    },
  },
  {
    id: "task_total_10",
    name: "把今天启动了",
    description: "累计完成 10 个任务",
    icon: "🌟",
    type: "AUTO",
    condition: { kind: "task_total", value: 10 },
  },
  {
    id: "task_total_50",
    name: "节奏渐入佳境",
    description: "累计完成 50 个任务",
    icon: "🔥",
    type: "AUTO",
    condition: { kind: "task_total", value: 50 },
  },
  {
    id: "task_total_100",
    name: "持续发光的人",
    description: "累计完成 100 个任务",
    icon: "✨",
    type: "AUTO",
    condition: { kind: "task_total", value: 100 },
  },
  {
    id: "task_total_300",
    name: "自律旅者",
    description: "累计完成 300 个任务",
    icon: "🏆",
    type: "AUTO",
    condition: { kind: "task_total", value: 300 },
  },
  {
    id: "learning_streak_3",
    name: "微光坚持",
    description: "连续 3 天完成认知/看课类任务",
    icon: "📖",
    type: "AUTO",
    condition: { kind: "category_streak", value: 3, extra: { categories: ["learning", "course", "认知"] } },
  },
  {
    id: "learning_streak_7",
    name: "知识流动",
    description: "连续 7 天完成认知/看课类任务",
    icon: "🧠",
    type: "AUTO",
    condition: { kind: "category_streak", value: 7, extra: { categories: ["learning", "course", "认知"] } },
  },
  {
    id: "body_level_3",
    name: "体力觉醒",
    description: "体力属性达到 Lv.3",
    icon: "💪",
    type: "AUTO",
    condition: { kind: "attribute_level", value: 3, extra: { attributeId: "body" } },
  },
  {
    id: "cleaning_stage_1",
    name: "清理副本 · 初章",
    description: "完成清理/垃圾类任务 10 次",
    icon: "🧼",
    type: "AUTO",
    condition: { kind: "tag_or_category_count", value: 10, extra: { tag: "room_cleanup", categories: ["cleaning", "清理"] } },
  },
  {
    id: "daily_coins_150",
    name: "奖励之光",
    description: "单日获得金币 ≥ 150",
    icon: "🪙",
    type: "AUTO",
    condition: { kind: "daily_coins", value: 150 },
  },
  {
    id: "daily_coins_300",
    name: "丰收之日",
    description: "单日获得金币 ≥ 300",
    icon: "💰",
    type: "AUTO",
    condition: { kind: "daily_coins", value: 300 },
  },
];
