export const TASK_CATEGORIES = [
  { key: "course", label: "课程", description: "看课与学习推进" },
  { key: "weight", label: "体重管理", description: "饮食与身体管理" },
  { key: "english", label: "英语", description: "英文输入与学习" },
  { key: "photo", label: "拍照", description: "拍摄与选片" },
  { key: "life", label: "生活", description: "房间净化与日常" },
  { key: "nightclub", label: "夜场", description: "夜场班次" },
  { key: "future", label: "人生主线", description: "自我探索" },
  { key: "other", label: "其他", description: "杂项任务" },
];

export const TASK_TEMPLATES = [
  // 统一数值策略：
  // 小任务（<=5分钟）：sanity +2~3，energy 0 或 -1。
  // 中等任务（10~30分钟）：sanity +4~7，energy 0~-2（成长任务默认 0~-1）。
  // 大任务（30分钟以上）：sanity +6~10，energy 0~-2（成长任务默认 0~-1），并提供更高 EXP/金币。
  // 夜场一班：energy -20、sanity -10（高消耗但高回报）。
  // 夜场二班：energy -40、sanity -20、health -5（更高回报，并暗示需要休息）。
  // 纯成长任务范围：course / english / photo / life / future / other（日常小任务）。
  {
    title: "看课 · 文姐",
    category: "course",
    subtype: "文姐",
    exp: 12,
    coinsReward: 10,
    effect: { sanity: 6, energy: -1 },
    cooldownMinutes: 30,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "看课 · 曲曲",
    category: "course",
    subtype: "曲曲",
    exp: 12,
    coinsReward: 10,
    effect: { sanity: 6, energy: -1 },
    cooldownMinutes: 30,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "看课 · 谢胜子",
    category: "course",
    subtype: "谢胜子",
    exp: 14,
    coinsReward: 12,
    effect: { sanity: 6, energy: -1 },
    cooldownMinutes: 45,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "看课 · 开智",
    category: "course",
    subtype: "开智",
    exp: 16,
    coinsReward: 12,
    effect: { sanity: 8, energy: -1 },
    cooldownMinutes: 60,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "每周称重",
    category: "weight",
    exp: 10,
    coinsReward: 8,
    effect: { sanity: 2 },
    cooldownMinutes: 60 * 24 * 7,
    isRepeatable: true,
  },
  {
    title: "正常吃一顿",
    category: "weight",
    exp: 8,
    coinsReward: 6,
    effect: { hunger: 12, energy: 4 },
    cooldownMinutes: 180,
    isRepeatable: true,
  },
  {
    title: "拒绝垃圾食品",
    category: "weight",
    exp: 12,
    coinsReward: 10,
    effect: { sanity: 6, health: 4 },
    cooldownMinutes: 120,
    isRepeatable: true,
    tags: ["no_junk_food"],
  },
  {
    title: "喝水",
    category: "weight",
    exp: 6,
    coinsReward: 4,
    effect: { health: 2 },
    cooldownMinutes: 60,
    isRepeatable: true,
  },
  {
    title: "接触英文 10 分钟",
    category: "english",
    exp: 10,
    coinsReward: 8,
    effect: { sanity: 4, energy: -1 },
    cooldownMinutes: 60,
    isRepeatable: true,
  },
  {
    title: "背单词 20 个",
    category: "english",
    exp: 12,
    coinsReward: 10,
    effect: { sanity: 5, energy: -1 },
    cooldownMinutes: 90,
    isRepeatable: true,
  },
  {
    title: "托福课 1 讲",
    category: "english",
    exp: 16,
    coinsReward: 12,
    effect: { sanity: 7, energy: -1 },
    cooldownMinutes: 120,
    isRepeatable: true,
  },
  {
    title: "准备衣服",
    category: "photo",
    exp: 8,
    coinsReward: 6,
    effect: { sanity: 3, energy: -1 },
    cooldownMinutes: 120,
    isRepeatable: true,
  },
  {
    title: "试穿",
    category: "photo",
    exp: 10,
    coinsReward: 8,
    effect: { sanity: 3, energy: -1 },
    cooldownMinutes: 180,
    isRepeatable: true,
  },
  {
    title: "拍摄",
    category: "photo",
    exp: 16,
    coinsReward: 14,
    effect: { sanity: 6, energy: -1 },
    cooldownMinutes: 240,
    isRepeatable: true,
  },
  {
    title: "选片",
    category: "photo",
    exp: 12,
    coinsReward: 10,
    effect: { sanity: 5, energy: -1 },
    cooldownMinutes: 180,
    isRepeatable: true,
  },
  {
    title: "倒垃圾",
    category: "life",
    exp: 6,
    coinsReward: 5,
    effect: { sanity: 3, energy: -1 },
    cooldownMinutes: 60,
    isRepeatable: true,
  },
  {
    title: "洗衣",
    category: "life",
    exp: 10,
    coinsReward: 8,
    effect: { sanity: 4, energy: -1 },
    cooldownMinutes: 180,
    isRepeatable: true,
  },
  {
    title: "整理 10 分钟",
    category: "life",
    exp: 8,
    coinsReward: 6,
    effect: { sanity: 4, energy: -1 },
    cooldownMinutes: 90,
    isRepeatable: true,
  },
  {
    title: "清理垃圾袋（房间净化）",
    category: "life",
    exp: 12,
    coinsReward: 10,
    effect: { sanity: 5, energy: -1 },
    cooldownMinutes: 120,
    isRepeatable: true,
    tags: ["room_cleanup"],
  },
  {
    title: "夜场一班",
    category: "nightclub",
    subtype: "一班",
    exp: 40,
    coinsReward: 40,
    effect: { energy: -20, hunger: -12, sanity: -10 },
    cooldownMinutes: 360,
    isRepeatable: true,
    requirements: { energy: 30 },
  },
  {
    title: "夜场二班",
    category: "nightclub",
    subtype: "二班",
    exp: 60,
    coinsReward: 60,
    effect: { energy: -40, hunger: -18, sanity: -20, health: -5 },
    cooldownMinutes: 480,
    isRepeatable: true,
    requirements: { energy: 50 },
    tags: ["nightclub_shift2"],
  },
  {
    title: "自我探索：我是谁",
    category: "future",
    exp: 20,
    coinsReward: 18,
    effect: { sanity: 9, energy: -1 },
    cooldownMinutes: 720,
    isRepeatable: false,
  },
  {
    title: "愿景清单",
    category: "future",
    exp: 18,
    coinsReward: 16,
    effect: { sanity: 8, energy: -1 },
    cooldownMinutes: 720,
    isRepeatable: false,
  },
  {
    title: "SWOT 分析",
    category: "future",
    exp: 22,
    coinsReward: 20,
    effect: { sanity: 10, energy: -1 },
    cooldownMinutes: 720,
    isRepeatable: false,
  },
  {
    title: "方向梳理",
    category: "future",
    exp: 20,
    coinsReward: 18,
    effect: { sanity: 9, energy: -1 },
    cooldownMinutes: 720,
    isRepeatable: false,
  },
  {
    title: "生活小任务：整理邮箱",
    category: "other",
    exp: 6,
    coinsReward: 4,
    effect: { sanity: 3, energy: -1 },
    cooldownMinutes: 120,
    isRepeatable: true,
  },
];
