export const TASK_CATEGORIES = [
  { key: "course", label: "课程", description: "看课与学习推进" },
  { key: "weight", label: "体重管理", description: "饮食与身体管理" },
  { key: "english", label: "英语", description: "英文输入与学习" },
  { key: "photo", label: "拍照", description: "拍摄与选片" },
  { key: "life", label: "生活", description: "房间净化与日常" },
  { key: "nightclub", label: "夜场", description: "夜场班次" },
  { key: "future", label: "人生主线", description: "自我探索" },
  { key: "other", label: "其他", description: "杂项任务" },
];

export const TASK_TEMPLATES = [
  {
    title: "看课 · 文姐",
    category: "course",
    subtype: "文姐",
    minutes: 60,
    difficulty: 2,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "看课 · 曲曲",
    category: "course",
    subtype: "曲曲",
    minutes: 60,
    difficulty: 2,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "看课 · 谢胜子",
    category: "course",
    subtype: "谢胜子",
    minutes: 60,
    difficulty: 2,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "看课 · 开智",
    category: "course",
    subtype: "开智",
    minutes: 75,
    difficulty: 3,
    isRepeatable: true,
    tags: ["course"],
  },
  {
    title: "每周称重",
    category: "weight",
    minutes: 10,
    difficulty: 1,
    isRepeatable: true,
  },
  {
    title: "正常吃一顿",
    category: "weight",
    minutes: 30,
    difficulty: 1,
    effect: { hunger: 25 },
    isRepeatable: true,
  },
  {
    title: "拒绝垃圾食品",
    category: "weight",
    minutes: 20,
    difficulty: 2,
    effect: { life: 4 },
    isRepeatable: true,
    tags: ["no_junk_food"],
  },
  {
    title: "喝水",
    category: "weight",
    minutes: 5,
    difficulty: 1,
    effect: { life: 2 },
    isRepeatable: true,
  },
  {
    title: "接触英文 10 分钟",
    category: "english",
    minutes: 10,
    difficulty: 2,
    isRepeatable: true,
  },
  {
    title: "背单词 20 个",
    category: "english",
    minutes: 20,
    difficulty: 2,
    isRepeatable: true,
  },
  {
    title: "托福课 1 讲",
    category: "english",
    minutes: 60,
    difficulty: 3,
    isRepeatable: true,
  },
  {
    title: "准备衣服",
    category: "photo",
    minutes: 20,
    difficulty: 1,
    isRepeatable: true,
  },
  {
    title: "试穿",
    category: "photo",
    minutes: 30,
    difficulty: 2,
    isRepeatable: true,
  },
  {
    title: "拍摄",
    category: "photo",
    minutes: 120,
    difficulty: 4,
    isRepeatable: true,
  },
  {
    title: "选片",
    category: "photo",
    minutes: 90,
    difficulty: 3,
    isRepeatable: true,
  },
  {
    title: "倒垃圾",
    category: "life",
    minutes: 10,
    difficulty: 1,
    isRepeatable: true,
  },
  {
    title: "洗衣",
    category: "life",
    minutes: 60,
    difficulty: 2,
    isRepeatable: true,
  },
  {
    title: "整理 10 分钟",
    category: "life",
    minutes: 10,
    difficulty: 1,
    isRepeatable: true,
  },
  {
    title: "清理垃圾袋（房间净化）",
    category: "life",
    minutes: 30,
    difficulty: 2,
    isRepeatable: true,
    tags: ["room_cleanup"],
  },
  {
    title: "短暂休息 15 分钟",
    category: "life",
    kind: "rest",
    minutes: 15,
    difficulty: 1,
    effect: { life: 10, sanity: 5 },
    isRepeatable: true,
    tags: ["rest"],
  },
  {
    title: "补觉 / 睡一会儿",
    category: "life",
    kind: "rest",
    minutes: 120,
    difficulty: 1,
    effect: { life: 10, sanity: 5 },
    isRepeatable: true,
    tags: ["sleep"],
  },
  {
    title: "夜场一班",
    category: "nightclub",
    subtype: "一班",
    minutes: 240,
    difficulty: 4,
    isRepeatable: true,
  },
  {
    title: "夜场二班",
    category: "nightclub",
    subtype: "二班",
    minutes: 360,
    difficulty: 5,
    isRepeatable: true,
    tags: ["nightclub_shift2"],
  },
  {
    title: "自我探索：我是谁",
    category: "future",
    minutes: 90,
    difficulty: 4,
    isRepeatable: false,
  },
  {
    title: "愿景清单",
    category: "future",
    minutes: 90,
    difficulty: 4,
    isRepeatable: false,
  },
  {
    title: "SWOT 分析",
    category: "future",
    minutes: 120,
    difficulty: 4,
    isRepeatable: false,
  },
  {
    title: "方向梳理",
    category: "future",
    minutes: 90,
    difficulty: 4,
    isRepeatable: false,
  },
  {
    title: "生活小任务：整理邮箱",
    category: "other",
    minutes: 15,
    difficulty: 1,
    isRepeatable: true,
  },
];
